; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32H750VB]
platform = ststm32
board = genericSTM32H750VB
framework = arduino
platform_packages = 
	platformio/tool-openocd@3.1200.0
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
monitor_speed = 115200
lib_deps = waspinator/AccelStepper@^1.64

[platformio]
default_envs = genericSTM32H750VB
description = It's true document
