[platformio]
default_envs = genericSTM32H750VB

[env:genericSTM32H750VB]
platform = ststm32
board = genericSTM32H750VB_cmsis_dap
framework = arduino
monitor_speed = 115200
lib_deps = 
	waspinator/AccelStepper@^1.64
	mathertel/OneButton@^2.6.2
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
; 仅编译正式入口；route_chassis_main.inc 由 main.cpp 在命名空间中包含。
build_src_filter = -<*> +<main.cpp>
